language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.06
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
  - opam update
  - opam install -y ppx_deriving
  - opam install -y menhir
  - opam install -y core_kernel.v0.10.0
  - opam install -y ctypes
  - opam install -y uutf
  - opam install -y result
  - opam install -y bitv
  - opam install -y batteries
  - opam install -y yojson
  - opam install -y camlimages
  - opam install -y camlpdf.2.2.1+satysfi
  - opam install -y otfm.0.3.0+satysfi
  - eval `opam config env`
script:
  - make all
